# Generated by Django 5.1.4 on 2026-07-16 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_source',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('ENTRA', 'Microsoft Entra'), ('INTERNAL_MASTER', 'Internal Master')], db_index=True, default='LEGACY', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='last_authenticated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrador'), ('ADMINISTRADOR', 'Administrador'), ('QUALIDADE', 'Qualidade'), ('AUDITOR', 'Auditor'), ('GESTOR', 'Gestor'), ('COLABORADOR', 'Colaborador')], db_index=True, default='COLABORADOR', max_length=32),
        ),
        migrations.CreateModel(
            name='AuthAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ENTRA', 'Entra'), ('MASTER', 'Master'), ('LEGACY', 'Legacy')], max_length=16)),
                ('event', models.CharField(max_length=64)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=16)),
                ('tenant_id', models.CharField(blank=True, default='', max_length=64)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('jti', models.CharField(blank=True, default='', max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('detail', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoria de autenticação',
                'verbose_name_plural': 'Eventos de auditoria de autenticação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntraIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('photo_url', models.URLField(blank=True, default='')),
                ('last_claims_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_authenticated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entra_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identidade Entra',
                'verbose_name_plural': 'Identidades Entra',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'object_id'), name='uniq_entra_tenant_object')],
            },
        ),
    ]
