# Generated by Django 5.1.4 on 2026-07-01 11:54

import django.db.models.deletion
import inspections.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('regional', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('unit_type', models.CharField(blank=True, default='', max_length=255)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('admin_coordinator', models.CharField(blank=True, default='', max_length=255)),
                ('general_director', models.CharField(blank=True, default='', max_length=255)),
                ('characterization', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('item_code', models.CharField(max_length=20)),
                ('question', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.checklistsection')),
            ],
            options={
                'ordering': ['section__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_preenchimento', 'Em preenchimento'), ('revisao', 'Revisão'), ('finalizada', 'Finalizada')], default='rascunho', max_length=20)),
                ('methodology_text', models.TextField(blank=True, default='')),
                ('objectives_text', models.TextField(blank=True, default='')),
                ('limitations_text', models.TextField(blank=True, default='')),
                ('final_considerations_text', models.TextField(blank=True, default='')),
                ('general_info_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspections.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('C', 'Conforme'), ('NC', 'Não conforme'), ('NA', 'Não aplicável')], max_length=2, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('recommendation', models.TextField(blank=True, default='')),
                ('normative', models.TextField(blank=True, default='')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.checklistitem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='inspections.inspection')),
            ],
            options={
                'unique_together': {('inspection', 'checklist_item')},
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=inspections.models.photo_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspectionanswer')),
            ],
        ),
    ]
