# Generated by Django 5.1.4 on 2026-07-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='cover_diretor_executivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cover_diretoria_executiva',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cover_gerencia_geral',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cover_gerencia_meio_ambiente',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cover_gerencia_sst',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cover_gerente_geral',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cover_gerente_meio_ambiente',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cover_gerente_sst',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
