# Generated by Django 5.1.4 on 2026-07-02 12:54

import inspections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_sync_client_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='address_photo',
            field=models.ImageField(blank=True, null=True, upload_to=inspections.models.inspection_address_photo_upload_to),
        ),
    ]
