diretoria_executiva: "Diretoria Executiva de SSMA"
diretor_executivo: "Jorge Araújo"
gerencia_geral: "Gerencia Geral de Qualidade, Saúde Segurança e Meio Ambiente"
gerente_geral: "Leonardo Espíndola"
gerencia_sst: "Gerencia de Saúde Segurança do Trabalho"
gerente_sst: "Thiago Gléria"
gerencia_meio_ambiente: "Gerencia de Meio Ambiente"
gerente_meio_ambiente: "Jaciara Aguiar"
regional: "Norte"
cidade: "São Luís/MA"
