# CloudPanel — Vhost Custom → apiinspecao.iadvh.org.br

location ^~ /static/ {
    alias /home/iadvh-apiinspecao/htdocs/apiinspecao.iadvh.org.br/backend/staticfiles/;
    expires 30d;
    add_header Cache-Control "public";
    access_log off;
}
